apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: publish-video-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publish-video-app
      version: v1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: docker.io/istio/examples-helloworld-v2
        imagePullPolicy: IfNotPresent
        name: helloworld
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          requests:
            cpu: 100m
status: {}
